name: WifiMirror
description: "Cross-platform screen sharing app for local WiFi networks"
publish_to: 'none'

version: 1.1.1+3

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  # Network Service Discovery
  bonsoir: ^6.0.0
  
  # WebRTC for screen streaming
  flutter_webrtc: ^0.12.8
  
  # Utilities
  uuid: ^4.5.1
  shared_preferences: ^2.3.5
  permission_handler: ^11.3.1
  encrypt: ^5.0.3
  crypto: ^3.0.6
  connectivity_plus: ^6.1.4
  device_info_plus: ^11.4.0
  
  # Platform-specific utilities
  path_provider: ^2.1.5
  wakelock_plus: ^1.2.10
  
  # WebSocket support (for web platform signaling)
  web_socket_channel: ^3.0.3
  
  # URL Launcher for opening download links
  url_launcher: ^6.2.5
  
  # Router for deep linking and navigation
  go_router: ^14.6.2
  file_picker: ^10.3.9
  just_audio: ^0.10.5
  mime: ^2.0.0
  shelf: ^1.4.2
  shelf_web_socket: ^3.0.0
  shelf_static: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/img/
#    - assets/fonts/
    - assets/web_app/
    - assets/web_app/assets/
    - assets/web_app/assets/fonts/
    - assets/web_app/assets/packages/
    - assets/web_app/assets/packages/cupertino_icons/
    - assets/web_app/assets/packages/cupertino_icons/assets/
    - assets/web_app/assets/packages/wakelock_plus/
    - assets/web_app/assets/packages/wakelock_plus/assets/
    - assets/web_app/assets/shaders/
    - assets/web_app/canvaskit/
    - assets/web_app/canvaskit/chromium/
    - assets/web_app/icons/
